sonar.projectKey=encryption
sonar.sources=job-results,lib,util
sonar.tests=.
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=node_modules/**,coverage/**,testing/**,eslint.config.mjs,vitest.config.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info