name: Checks
on:
  push:
    branches: [main]
  pull_request:

jobs:
  all:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Run Specs
        run: npm run ci
